#include "parser.h"

#define VERIFY 0
// parameters
// f_para: the data file
// loggps: an array of struct where to store data,
//         pass the head pointer here
void parse_loggpo(const char* f_para, pLoggpoPara logps) {
    memset(logps, 0, sizeof(LoggpoPara));
    FILE* pf_para = NULL;
    pf_para = fopen(f_para,"r");
    if (! pf_para) {
        printf("file open failed!\n");
    }

    // read the file
    int index = 0;
    int LINES = 200;
    char line[LINES];
    while (line == fgets(line, LINES, pf_para)) {
        pLoggpoPara p = &(logps[index]); 
        int ret = sscanf(line, "%d%lf%lf%lf%lf%lf%lf%lf", 
          &p->size, &p->os, &p->or, &p->ov, &p->sr, &p->gap, &p->rtt, &p->rtt100);
        if (ret == 8) ++index;
    }
    // verify
    #if VERIFY
    for (int i = 0; i < index; ++ i) {
        pLoggpoPara p = &(logps[i]); 
        printf("\t%d\t%lf\t%lf\t%lf\t%lf\t%lf\t%lf\t%lf\n",
          p->size, p->os, p->or, p->ov, p->sr, p->gap, p->rtt, p->rtt100);
    }
    #endif
}

// this function tells you which benchmark we are in
IMBState test_benchmark(const char* line) {
    bool comment = false;
    for (int i = 0; i < strlen(line); ++ i) {
        if (line[i] == '#') {
            comment = true;
            break;
        }
    }
    if (comment == false) return data;

    if (strcmp(line,"# All processes entering MPI_Finalize\n") == 0) {
        //printf("Finalize\n");
        return end;
    }

    char str0[100], str1[100], str2[100];
    int ret = sscanf(line, "%s%s%s", str0, str1, str2);
    if (ret != 3) return init;
    if (strcmp(str1,"Benchmarking") != 0) return init;

    IMBState s = unknown;
    if (strcmp(str2,"Barrier") == 0) s = barrier;
    else if (strcmp(str2,"Bcast") == 0) s = bcast;
    else if (strcmp(str2,"Reduce") == 0) s = reduce;
    else if (strcmp(str2,"Gather") == 0) s = gather;
    else if (strcmp(str2,"Allreduce") == 0) s = allreduce;
    else if (strcmp(str2,"Allgather") == 0) s = allgather;
    else s = unknown;
    return s;
}
    

// parameters
// f_para: data file generated by IMB
// pimb: a pointer to IMBPara, which stores IMB data
void parse_imb(const char* f_para, pIMBPara pimb) {
    memset(pimb, 0, sizeof(IMBPara));
    FILE* pf_para = NULL;
    pf_para = fopen(f_para,"r");
    if (! pf_para) {
        printf("file open failed!\n");
    }

    // read the file
    int proc=-1;
    int LINES = 200;
    char line[LINES];
    char str0[100], str1[100], str2[100];
    IMBState s = init, ns;
    // read a line
    while (line == fgets(line, LINES, pf_para)) {
        //printf("%s,%d\n",line,s);
        // empty line
        if (strlen(line) == 0) {
            ns = data;
            continue;
        }
            
        ns = test_benchmark(line);
        switch (s) {
        case init:
            if (ns >= init && ns <= end)
                s = ns;
            break;
        case barrier:
            if (ns == init) {
                int ret = sscanf(line, "%s%s%s%d", str0, str1, str2, &proc);
                if (ret != 4) break;
                if (strcmp(str1,"#processes") == 0)
                    pimb->barrier[pimb->n_barrier].proc = proc;
            }
            else if (ns == data) {
                int rep;
                double t0, t1, t2;
                int ret = sscanf(line,"%d%lf%lf%lf", &rep, &t0, &t1, &t2);
                if (ret != 4) { 
                    //printf("Read parameters error\n");
                    break;
                }
                pimb->barrier[pimb->n_barrier].t_min = t0;
                pimb->barrier[pimb->n_barrier].t_max = t1;
                pimb->barrier[pimb->n_barrier].t_avg = t2;
            }
            else if (ns == barrier) {
                ++ pimb->n_barrier;
            }
            else {
                s = ns;
                ++ pimb->n_barrier;
            }
            break;
        case bcast:
            if (ns == init) {
                int ret = sscanf(line,"%s%s%s%d",str0,str1,str2,&proc);
                if (ret != 4) break;
                if (strcmp(str1,"#processes") == 0)
                    pimb->bcast[pimb->n_bcast].proc = proc;
            }
            else if (ns == data) {
                int bytes, rep;
                double t0, t1, t2;
                int ret = sscanf(line,"%d%d%lf%lf%lf",&bytes,&rep,&t0,&t1,&t2);
                if (ret != 5) {
                    //printf("Read parameters error\n");
                    break;
                }
                int n_byte = pimb->bcast[pimb->n_bcast].n_byte ++;
                pimb->bcast[pimb->n_bcast].para[n_byte].bytes = bytes;
                pimb->bcast[pimb->n_bcast].para[n_byte].t_min = t0;
                pimb->bcast[pimb->n_bcast].para[n_byte].t_max = t1;
                pimb->bcast[pimb->n_bcast].para[n_byte].t_avg = t2;
            }
            else if (ns == bcast ) {
                ++ pimb->n_bcast;
            }
            else {
                s = ns;
                ++ pimb->n_bcast;
            }
            break;
        case reduce:
            if (ns == init) {
                int ret = sscanf(line,"%s%s%s%d",str0,str1,str2,&proc);
                if (ret != 4) break;
                if (strcmp(str1,"#processes") == 0)
                    pimb->reduce[pimb->n_reduce].proc = proc;
            }
            else if (ns == data) {
                int bytes, rep;
                double t0, t1, t2;
                int ret = sscanf(line,"%d%d%lf%lf%lf",&bytes,&rep,&t0,&t1,&t2);
                if (ret != 5) {
                    //printf("Read parameters error\n");
                    break;
                }
                int n_byte = pimb->reduce[pimb->n_reduce].n_byte ++;
                pimb->reduce[pimb->n_reduce].para[n_byte].bytes = bytes;
                pimb->reduce[pimb->n_reduce].para[n_byte].t_min = t0;
                pimb->reduce[pimb->n_reduce].para[n_byte].t_max = t1;
                pimb->reduce[pimb->n_reduce].para[n_byte].t_avg = t2;
            }
            else if (ns == reduce ) {
                ++ pimb->n_reduce;
            }
            else {
                s = ns;
                ++ pimb->n_reduce;
            }
            break;
        case gather:
            if (ns == init) {
                int ret = sscanf(line,"%s%s%s%d",str0,str1,str2,&proc);
                if (ret != 4) break;
                if (strcmp(str1,"#processes") == 0)
                    pimb->gather[pimb->n_gather].proc = proc;
            }
            else if (ns == data) {
                int bytes, rep;
                double t0, t1, t2;
                int ret = sscanf(line,"%d%d%lf%lf%lf",&bytes,&rep,&t0,&t1,&t2);
                if (ret != 5) {
                    //printf("Read parameters error\n");
                    break;
                }
                int n_byte = pimb->gather[pimb->n_gather].n_byte ++;
                pimb->gather[pimb->n_gather].para[n_byte].bytes = bytes;
                pimb->gather[pimb->n_gather].para[n_byte].t_min = t0;
                pimb->gather[pimb->n_gather].para[n_byte].t_max = t1;
                pimb->gather[pimb->n_gather].para[n_byte].t_avg = t2;
            }
            else if (ns == gather ) {
                ++ pimb->n_gather;
            }
            else {
                s = ns;
                ++ pimb->n_gather;
            }
            break;
        case allreduce:
            if (ns == init) {
                int ret = sscanf(line,"%s%s%s%d",str0,str1,str2,&proc);
                if (ret != 4) break;
                if (strcmp(str1,"#processes") == 0)
                    pimb->allreduce[pimb->n_allreduce].proc = proc;
            }
            else if (ns == data) {
                int bytes, rep;
                double t0, t1, t2;
                int ret = sscanf(line,"%d%d%lf%lf%lf",&bytes,&rep,&t0,&t1,&t2);
                if (ret != 5) {
                    //printf("Read parameters error\n");
                    break;
                }
                int n_byte = pimb->allreduce[pimb->n_allreduce].n_byte ++;
                pimb->allreduce[pimb->n_allreduce].para[n_byte].bytes = bytes;
                pimb->allreduce[pimb->n_allreduce].para[n_byte].t_min = t0;
                pimb->allreduce[pimb->n_allreduce].para[n_byte].t_max = t1;
                pimb->allreduce[pimb->n_allreduce].para[n_byte].t_avg = t2;
            }
            else if (ns == allreduce ) {
                ++ pimb->n_allreduce;
            }
            else {
                s = ns;
                ++ pimb->n_allreduce;
            }
            break;
        case allgather:
            if (ns == init) {
                int ret = sscanf(line,"%s%s%s%d",str0,str1,str2,&proc);
                if (ret != 4) break;
                if (strcmp(str1,"#processes") == 0)
                    pimb->allgather[pimb->n_allgather].proc = proc;
            }
            else if (ns == data) {
                int bytes, rep;
                double t0, t1, t2;
                int ret = sscanf(line,"%d%d%lf%lf%lf",&bytes,&rep,&t0,&t1,&t2);
                if (ret != 5) {
                    //printf("Read parameters error\n");
                    break;
                }
                int n_byte = pimb->allgather[pimb->n_allgather].n_byte ++;
                pimb->allgather[pimb->n_allgather].para[n_byte].bytes = bytes;
                pimb->allgather[pimb->n_allgather].para[n_byte].t_min = t0;
                pimb->allgather[pimb->n_allgather].para[n_byte].t_max = t1;
                pimb->allgather[pimb->n_allgather].para[n_byte].t_avg = t2;
            }
            else if (ns == allgather ) {
                ++ pimb->n_allgather;
            }
            else {
                s = ns;
                ++ pimb->n_allgather;
            }
            break;
        case end:
        case data:
        case unknown:
        default:
            break;
        }
    }

    #if VERIFY
    printf("Barrier\n-----------\n");
    for (int i = 0; i < pimb->n_barrier; ++ i) {
        printf("proc: %d, tmin: %8f tmax: %8f tavg: %8f\n",
          pimb->barrier[i].proc, pimb->barrier[i].t_min,
          pimb->barrier[i].t_max, pimb->barrier[i].t_avg);
    }
    printf("\nBcast\n-----------\n");
    for (int i = 0; i < pimb->n_bcast; ++ i) {
        printf("proc: %d\n", pimb->bcast[i].proc);
        for (int j = 0; j < pimb->bcast[i].n_byte; ++ j) {
            printf(" bytes: %d, tmin: %8f tmax: %8f tavg %8f\n",
              pimb->bcast[i].para[j].bytes,
              pimb->bcast[i].para[j].t_min,
              pimb->bcast[i].para[j].t_max,
              pimb->bcast[i].para[j].t_avg);
        }
    }
    printf("\nReduce\n-----------\n");
    for (int i = 0; i < pimb->n_reduce; ++ i) {
        printf("proc: %d\n", pimb->reduce[i].proc);
        for (int j = 0; j < pimb->reduce[i].n_byte; ++ j) {
            printf(" bytes: %d, tmin: %8f tmax: %8f tavg %8f\n",
              pimb->reduce[i].para[j].bytes,
              pimb->reduce[i].para[j].t_min,
              pimb->reduce[i].para[j].t_max,
              pimb->reduce[i].para[j].t_avg);
        }
    }
    printf("\nGather\n-----------\n");
    for (int i = 0; i < pimb->n_gather; ++ i) {
        printf("proc: %d\n", pimb->gather[i].proc);
        for (int j = 0; j < pimb->gather[i].n_byte; ++ j) {
            printf(" bytes: %d, tmin: %8f tmax: %8f tavg %8f\n",
              pimb->gather[i].para[j].bytes,
              pimb->gather[i].para[j].t_min,
              pimb->gather[i].para[j].t_max,
              pimb->gather[i].para[j].t_avg);
        }
    }
    printf("\nAllreduce\n-----------\n");
    for (int i = 0; i < pimb->n_allreduce; ++ i) {
        printf("proc: %d\n", pimb->allreduce[i].proc);
        for (int j = 0; j < pimb->allreduce[i].n_byte; ++ j) {
            printf(" bytes: %d, tmin: %8f tmax: %8f tavg %8f\n",
              pimb->allreduce[i].para[j].bytes,
              pimb->allreduce[i].para[j].t_min,
              pimb->allreduce[i].para[j].t_max,
              pimb->allreduce[i].para[j].t_avg);
        }
    }
    printf("\nAllgather\n-----------\n");
    for (int i = 0; i < pimb->n_allgather; ++ i) {
        printf("proc: %d\n", pimb->allgather[i].proc);
        for (int j = 0; j < pimb->allgather[i].n_byte; ++ j) {
            printf(" bytes: %d, tmin: %8f tmax: %8f tavg %8f\n",
              pimb->allgather[i].para[j].bytes,
              pimb->allgather[i].para[j].t_min,
              pimb->allgather[i].para[j].t_max,
              pimb->allgather[i].para[j].t_avg);
        }
    }
    #endif
}

// this main is for test parser
/*
int main() {
    parse_loggpo("cmp_para", logps);
    parse_imb("coll_para", &imb);
    return 0;
}
*/

          
        
